### ISSUE TITLE
Function

### ISSUE THREAD

**Issue by iitalics** [nanocaml/nanocaml#3]
## Language definitions

Likely, we'll use polymorphic variants, which makes generating code for type definitions and patterns very straightforward.

## Extending languages

By storing all relevant information about nonterminals, we can easily recreate AST types with certain forms added/removed.

## Entry points

Do we need entry points? I need to be more acquainted with nanopass to see why entries exist and if they are necessary. I guess I just don't see why not just declare functions for each type and then specify manually at the end when composing all of the passes.

## Catamorphisms

Difficult.

1. **Don't infer catamorphisms**
Catamorphism function is specified in the function explicitly. This would make it easier for us but would make nanopass significantly more verbose.

2. **Nominal catamorphism inference**
Infer catamorphism function from the name of the type. If the type being matched on is `expr`, then use the `expr` function. 

3. **Type inference**
We might be able to leverage typpx to get type information to infer the catamorphism. This would be awesome, but more difficult. Maybe something to think about in a v2

## Catamorphisms outside of passes

What if the programmer wants to match on a type, outside of a pass function? 

1. How do we know what type they are matching on? Without typpx, this needs to be specified explicitly. Or try to "infer" it by the provided patterns (assuming that no two nonterminals share a variant)

2. How do we know which catamorphism to apply? I would guess a common pattern would be to have a helper function recursively descend the given type. How does this play into cata inference?

**Comment by OhadRau** [comment]
Pretty sure this is all done 👍
